version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directories:
      - "/contrib/charts/dragonfly"
      - "/tools/replay"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories:
      - "/tests/dragonfly"
      - "/tools"
    schedule:
      interval: "weekly"
