name: benchmark-tests

on:
  schedule:
    - cron: "0 9 * * *" # run at 6 AM UTC
  workflow_dispatch:

jobs:
  benchmark:
    strategy:
      matrix:
        config:
          - apiVersion: "dragonflydb.io/v1alpha1"
            kind: "Dragonfly"
            metadata:
              labels:
                app.kubernetes.io/name: "dragonfly"
                app.kubernetes.io/instance: "dragonfly-sample"
                app.kubernetes.io/part-of: "dragonfly-operator"
                app.kubernetes.io/managed-by: "kustomize"
                app.kubernetes.io/created-by: "dragonfly-operator"
              name: "dragonfly-sample"
            spec:
              image: "ghcr.io/dragonflydb/dragonfly-weekly:latest"
              args: ["--cache_mode"]
              replicas: 2
              resources:
                requests:
                  cpu: "4"
                  memory: "2000Mi"
                limits:
                  cpu: "4"
                  memory: "2000Mi"

    runs-on: [self-hosted, linux, x86, benchmark]

    container:
      image: ghcr.io/romange/benchmark-dev:latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: KinD Cluster
        uses: container-tools/kind-action@v2.0.3
        with:
          kubectl_version: v1.28.0
          registry: false
      - name: Install the CRD and Operator
        run: |
          # Install the CRD and Operator
          kubectl apply -f https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/main/manifests/dragonfly-operator.yaml
      - name: Apply Configuration
        run: |
          echo '${{ toJson(matrix.config) }}' | kubectl apply -f -

      - name: Wait For Service
        run: |
          kubectl wait dragonfly/dragonfly-sample --for=jsonpath='{.status.phase}'=ready --timeout=120s
          kubectl wait pods --selector app=dragonfly-sample --for condition=Ready --timeout=120s
          kubectl describe pod dragonfly-sample-0

      - name: Run Benchmark
        run: |
          nohup kubectl port-forward service/dragonfly-sample 6379:6379 &
          sleep 5
          redis-cli ping
          # run small memtier benchmark
          memtier_benchmark  --pipeline=30 --key-maximum=10000 -c 10 -t 8 --requests=500000 --expiry-range=10-100 --reconnect-interval=10000 --distinct-client-seed --hide-histogram

      - name: Server checks
        run: |
          pip3 install -r tools/requirements.txt
          python tools/benchmark_checks.py
