name: Regression Tests

on:
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:




jobs:
  build-n-test:
    strategy:
      matrix:
        # Test of these containers
        container: ["ubuntu-dev:20"]
        build-type: [Debug, Release]
        runner: [ubuntu-latest, [self-hosted, linux, ARM64]]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 45

    container:
      image: ghcr.io/romange/${{ matrix.container }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Print cpu info
        run:  cat /proc/cpuinfo

      - name: Configure & Build
        run: |
          apt update && apt install -y pip
          cmake -B ${GITHUB_WORKSPACE}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -GNinja \
                -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

          cd ${GITHUB_WORKSPACE}/build  && ninja dragonfly
          pwd
          ls -l ..

      - name: Run PyTests
        timeout-minutes: 10
        run: |
          ls -l ${GITHUB_WORKSPACE}/
          cd ${GITHUB_WORKSPACE}/tests
          echo "Current commit is ${{github.sha}}"
          pip install -r dragonfly/requirements.txt
          export DRAGONFLY_PATH="${GITHUB_WORKSPACE}/build/dragonfly" # used by PyTests

          pytest -sxvr dragonfly --ignore=dragonfly/replication_test.py
      - name: Run PyTests replication test
        if: ${{ matrix.runner  == 'ubuntu-latest' }}
        timeout-minutes: 15
        run: |
          cd ${GITHUB_WORKSPACE}/tests
          export DRAGONFLY_PATH="${GITHUB_WORKSPACE}/build/dragonfly" # used by PyTests
          pytest -xvs dragonfly/replication_test.py --df alsologtostderr --df enable_multi_shard_sync=true
          pytest -xvs dragonfly/replication_test.py --df alsologtostderr --df enable_multi_shard_sync=false

      - name: Send notification on failure
        if: failure() || cancelled()
        run: |
          curl -s \
            -X POST \
            -H 'Content-Type: application/json' \
            '${{ secrets.GSPACES_BOT_DF_BUILD }}' \
            -d '{"text": "Unforunately the tests of dragonfly build are not passed :( \n The commit is ${{github.sha}}	"}'
